version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'dev'
    schedule:
      interval: 'monthly'
      day: 'wednesday'
    commit-message:
      prefix: 'ğŸ“Œ'
    labels:
      - 'dependencies'
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'dev'
    schedule:
      interval: 'monthly'
      day: 'wednesday'
    commit-message:
      prefix: 'ğŸ‘·'
    labels:
      - 'dependencies'
